##### Checks run at pull request #####
# Check that urls in the content are not broken
url-checker: true
url_error_min: 0
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: true
# Spell check Rmds and quizzes
spell-check: true
spell_error_min: 0
# Style any R code
style-code: true
# Would you like a readability report on your markdowns?
readability-report: true
# Should URLs be tested periodically?
url-check-periodically: true

############ Metric Collection Destination ##############
### Options are "github" or "google"
data_dest: github
folder_path:

###### Calendly ######
refresh-calendly: no
calendly_googlesheet:

###### Citations ######
refresh-citations: yes
citation_papers: [
  "https://scholar.google.com/scholar?cites=12782135409483714808"
  ]
citation_googlesheet:

###### CRAN ######
refresh-cran: no
cran_packages:
cran_googlesheet:

###### GitHub ######
refresh-github: yes
github_repos: [
  jhudsl/AnVIL_Template
  ]
github_googlesheet:

###### Google Analytics ######
refresh-ga: yes
ga_property_ids: [ 
  377543643, 
  378491147
  ]
ga_googlesheet:

###### Google Forms ######
refresh-googleforms: no
google_forms:
googleforms_googlesheet:

###### Slido ######
refresh-slido: no
drive_id:
slido_googlesheet:

###### YouTube ######
refresh-youtube: yes
video_ids: [ 
  kn5msvMflgM, 
  0PRCFkLZOeo 
  ]
youtube_googlesheet:

##### Renderings run upon merge to main branch #####
# Rendering each platform's content
render-website: rmd_web

################## DOCKER #######################
# What docker image should be used for rendering?
# The default is cansav09/metricminer:main
rendering-docker-image: 'jhudsl/base_ottr:main'
# What docker image should be to get the data?
data-image: 'jhudsl/ottr_metrics:dev_test'
